name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please give as much detail as you can, and include steps to reproduce the problem.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Vincent are you using?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error/Crash log
      description: Please copy and paste any relevant log output.
      render: text