extends Label

func _ready() -> void:
	var app_name = ProjectSettings.get_setting("application/config/name")
	var app_version = ProjectSettings.get_setting("application/config/version")
	text = app_name + " " + app_version
	
	# gets git revision hash
	# this file is automatically generated by github actions
	var commit = FileAccess.get_file_as_string("res://commit.txt").strip_edges(true, true)
	
	# string length will be 0 if the file doesnt exist
	if commit.length() != 0:
		text += " (build %s)" % commit
