name: Snapshot Builds
on: 
  push:
    branches:
      - main

jobs:
  build-snapshot:
    strategy:
      # allow other OS snapshots to build even if one fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Revision Hash
        run: 
          REVISION=$(git rev-parse --short HEAD)
          echo "SHA_SHORT=$REVISION" >> $GITHUB_ENV
          echo "$REVISION" > ./commit.txt
      
      - name: Set Up Godot
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: 4.4.0
          use-dotnet: false
          include-templates: true

      - name: Compile Application (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "build/windows"
          godot --headless --export-release "windows x86_64" "build/windows/vincent-windows-x86_64.exe"

      - name: Compile Application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "build/linux"
          godot --headless --export-release "linux x86_64" "build/linux/vincent-linux.x86_64"

      - name: Upload Windows Snapshot
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SNAPSHOT-${{ env.SHA_SHORT }}-vincent-windows-x86_64
          path: build/windows/*
      
      - name: Upload Linux Snapshot
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SNAPSHOT-${{ env.SHA_SHORT }}-vincent-linux-x86_64
          path: build/linux/*