name: Issue Organization
on: 
  issues:
    types:
      - opened
permissions:
  issues: write
  contents: read

jobs:
  assign-label-and-project:
    runs-on: [ubuntu-latest]
    steps:
      - name: Assign to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/sharkaccino/projects/5
          github-token: ${{ secrets.ISSUE_ORGANIZATION }}
      - name: Add Triage Label
        if: (success() || failure()) && github.event.issue.labels[0] == null # skip if issue already has labels
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0