name: Issue Organization
on: 
  issues:
    types:
      - opened
permissions:
  issues: write
  contents: read
env:
  MY_GITHUB_TOKEN: ${{ github.token }}

jobs:
  assign-label-and-project:
    runs-on: [ubuntu-latest]
    steps:
      - name: Assign to Project
        uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: https://github.com/users/sharkaccino/projects/5
      - name: Add Triage Label
        if: success() || failure()
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ github.token }}
          enable-versioned-regex: 0